using Application.Exceptions;
using DataAccess;
using Domain;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class InitialDataController : ControllerBase
    {
        private readonly UpWorkContext _context;

        public InitialDataController(UpWorkContext context)
        {
            _context = context;
        }

        // GET: api/<InitialDataController>
        [HttpGet]
        public IActionResult Get()
        {
            if(_context.Experiences.Any())
            {
                throw new ConflictException("Data already exists");
            }
            Experience Entry = new()
            {
                Name = "Entry level",
            };
            Experience Intermediate = new()
            {
                Name = "Intermediate",
            };
            Experience Expert = new()
            {
                Name = "Expert",
            };
            Language English = new()
            {
                Name = "English"
            };
            Language German = new()
            {
                Name = "German"
            };
            Language French = new()
            {
                Name = "French"
            };
            Language Spanish = new()
            {
                Name = "Spanish"
            };
            Language Italian = new()
            {
                Name = "Italian"
            };
            WorkHour LessThan30Hrs = new()
            {
                Name = "Less than 30 hrs/week"
            };
            WorkHour MoreThan30Hrs = new()
            {
                Name = "More than 30 hrs/week"
            };
            SalaryType Fixed = new()
            {
                Type = "Fixed-price"
            };
            SalaryType Hourly = new()
            {
                Type = "Hourly"
            };
            LanguageProficiencyLevel Basic = new()
            {
                Level = "Basic"
            };
            LanguageProficiencyLevel Conversational = new()
            {
                Level = "Conversational"
            };
            LanguageProficiencyLevel Fluent = new()
            {
                Level = "Fluent"
            };
            LanguageProficiencyLevel Native = new()
            {
                Level = "Native"
            };
            _context.Files.Add(new Domain.File
            {
                Path = "/images/users/default.jpg",
                Extension = ".jpg",
                Size = 4220
            });
            _context.LanguageProficiencyLevels.AddRange(Basic, Conversational, Fluent, Native);
            _context.SalaryTypes.AddRange(Fixed, Hourly);
            _context.WorkHours.AddRange(LessThan30Hrs, MoreThan30Hrs);
            _context.Languages.AddRange(English, German, French, Spanish, Italian);
            _context.Experiences.AddRange(Entry, Intermediate, Expert);
            _context.Skills.AddRange(
                new Skill { Name = "Active Directory"},
                new Skill { Name = "ActiveMQ"},
                new Skill { Name = "ActiveX"},
                new Skill { Name = "ADO"},
                new Skill { Name = "ADO.NET"},
                new Skill { Name = "Adobe"},
                new Skill { Name = "Adobe Acrobat"},
                new Skill { Name = "Adobe After Effects"},
                new Skill { Name = "Adobe Creative Suite"},
                new Skill { Name = "Adobe Dreamweaver"},
                new Skill { Name = "Adobe Fireworks"},
                new Skill { Name = "Adobe Flash"},
                new Skill { Name = "Adobe Illustrator"},
                new Skill { Name = "Adobe InDesign"},
                new Skill { Name = "Adobe Photoshop"},
                new Skill { Name = "Adobe Premiere"},
                new Skill { Name = "Adobe Reader"},
                new Skill { Name = "Adobe Systems"},
                new Skill { Name = "Adobe XD"},
                new Skill { Name = "Agile"},
                new Skill { Name = "Agile Methodologies"},
                new Skill { Name = "Agile Project Management"},
                new Skill { Name = "AJAX"},
                new Skill { Name = "Akka"},
                new Skill { Name = "Algorithms"},
                new Skill { Name = "Amazon"},
                new Skill { Name = "Amazon AWS"},
                new Skill { Name = "Amazon CloudFront"},
                new Skill { Name = "Amazon EC2"},
                new Skill { Name = "Amazon RDS"},
                new Skill { Name = "Amazon S3"},
                new Skill { Name = "Amazon Web Services"},
                new Skill { Name = "Android"},
                new Skill { Name = "Android Development"},
                new Skill { Name = "Android SDK"},
                new Skill { Name = "Angular"},
                new Skill { Name = "AngularJS"},
                new Skill { Name = "Ansible"},
                new Skill { Name = "Apache"},
                new Skill { Name = "API"},
                new Skill { Name = "API Development"},
                new Skill { Name = "API Management"},
                new Skill { Name = "APIs"},
                new Skill { Name = "App Development"},
                new Skill { Name = "App Store"},
                new Skill { Name = "Apple"},
                new Skill { Name = "Apple iOS"},
                new Skill { Name = "Apple Mac OS X"},
                new Skill { Name = "Apple Safari"},
                new Skill { Name = "Apple Xcode"},
                new Skill { Name = "Application Development"},
                new Skill { Name = "Application Lifecycle Management"},
                new Skill { Name = "Application Servers"},
                new Skill { Name = "Application Support"},
                new Skill { Name = "Application Testing"},
                new Skill { Name = "Applications"},
                new Skill { Name = "Architecture"},
                new Skill { Name = "Artificial Intelligence"},
                new Skill { Name = "ASP.NET"},
                new Skill { Name = "ASP.NET Core"},
                new Skill { Name = "ASP.NET MVC"},
                new Skill { Name = "ASP.NET Web API"},
                new Skill { Name = "ASP.NET Web Forms"},
                new Skill { Name = "ASP.NET Web Services"},
                new Skill { Name = "Assembler"},
                new Skill { Name = "ASW"},
                new Skill { Name = "Atlassian"},
                new Skill { Name = "Atlassian Confluence"},
                new Skill { Name = "Atlassian JIRA"},
                new Skill { Name = "Atlassian Stash"},
                new Skill { Name = "Atlassian Tools"},
                new Skill { Name = "Atom"},
                new Skill { Name = "Augmented Reality"},
                new Skill { Name = "AutoCAD"},
                new Skill { Name = "Automated Testing"},
                new Skill { Name = "Automation"},
                new Skill { Name = "AWS"},
                new Skill { Name = "AWS CloudFormation"},
                new Skill { Name = "AWS Lambda"},
                new Skill { Name = "AWS S3"},
                new Skill { Name = "AWS Services"},
                new Skill { Name = "Azure"},
                new Skill { Name = "Azure Active Directory"},
                new Skill { Name = "Azure Cloud Services"},
                new Skill { Name = "Azure Cosmos DB"},
                new Skill { Name = "Azure Data Factory"},
                new Skill { Name = "Azure DevOps"},
                new Skill { Name = "Azure Functions"},
                new Skill { Name = "Azure Logic Apps"},
                new Skill { Name = "Azure Machine Learning"},
                new Skill { Name = "Azure SQL Database"},
                new Skill { Name = "Azure Storage"},
                new Skill { Name = "Azure Virtual Machines"},
                new Skill { Name = "Azure Web Apps"},
                new Skill { Name = "Babel"},
                new Skill { Name = "Backbone.js"},
                new Skill { Name = "Bash"},
                new Skill { Name = "Bash Scripting"},
                new Skill { Name = "Basic"},
                new Skill { Name = "Big Data"},
                new Skill { Name = "Big Data Analytics"},
                new Skill { Name = "Big Data Technologies"},
                new Skill { Name = "Bitbucket"},
                new Skill { Name = "Blockchain"},
                new Skill { Name = "Blockchain Development"},
                new Skill { Name = "Blockchain Technologies"},
                new Skill { Name = "Bootstrap"},
                new Skill { Name = "Bower"},
                new Skill { Name = "Business Analysis"},
                new Skill { Name = "Business Intelligence"},
                new Skill { Name = "Business Process Management"},
                new Skill { Name = "C"},
                new Skill { Name = "C#"},
                new Skill { Name = "C++"},
                new Skill { Name = "C++ Programming"},
                new Skill { Name = "C++11"},
                new Skill { Name = "C++14"},
                new Skill { Name = "C++17"},
                new Skill { Name = "C++20"},
                new Skill { Name = "C++Builder"},
                new Skill { Name = "C++CLI"},
                new Skill { Name = "C++/CLI"},
                new Skill { Name = "C++/CX"},
                new Skill { Name = "C++/WinRT"},
                new Skill { Name = "CAD"},
                new Skill { Name = "CakePHP"},
                new Skill { Name = "Cassandra"},
                new Skill { Name = "CDN"},
                new Skill { Name = "Celery"},
                new Skill { Name = "CentOS"},
                new Skill { Name = "Chef"},
                new Skill { Name = "CI/CD"},
                new Skill { Name = "Cisco"},
                new Skill { Name = "Cisco Technologies"},
                new Skill { Name = "Citrix"},
                new Skill { Name = "Citrix XenApp"},
                new Skill { Name = "Citrix XenDesktop"},
                new Skill { Name = "Citrix XenServer"},
                new Skill { Name = "Clojure"},
                new Skill { Name = "Cloud"},
                new Skill { Name = "Cloud Computing"},
                new Skill { Name = "Cloud Foundry"},
                new Skill { Name = "Cloud Infrastructure"},
                new Skill { Name = "Cloud Security"},
                new Skill { Name = "Cloud Services"},
                new Skill { Name = "Cloud Storage"},
                new Skill { Name = "Cloud Technologies"},
                new Skill { Name = "Cloudflare"},
                new Skill { Name = "CMS"},
                new Skill { Name = "COBOL"},
                new Skill { Name = "CodeIgniter"},
                new Skill { Name = "CoffeeScript"},
                new Skill { Name = "ColdFusion"},
                new Skill { Name = "CompTIA"},
                new Skill { Name = "CompTIA A+"},
                new Skill { Name = "CompTIA Network+"},
                new Skill { Name = "CompTIA Security+"},
                new Skill { Name = "Computer Graphics"},
                new Skill { Name = "Computer Hardware"},
                new Skill { Name = "Computer Networking"},
                new Skill { Name = "Computer Science"},
                new Skill { Name = "Computer Security"},
                new Skill { Name = "Computer Vision"},
                new Skill { Name = "Computing"},
                new Skill { Name = "Continuous Integration"},
                new Skill { Name = "Cordova"},
                new Skill { Name = "Couchbase"},
                new Skill { Name = "CouchDB"},
                new Skill { Name = "CPanel"},
                new Skill { Name = "Cryptography"},
                new Skill { Name = "Crystal Reports"},
                new Skill { Name = "CSS"},
                new Skill { Name = "CSS3"},
                new Skill { Name = "Cucumber"},
                new Skill { Name = "CUDA"},
                new Skill { Name = "D3.js"},
                new Skill { Name = "Dart"},
                new Skill { Name = "Data Analysis"},
                new Skill { Name = "Data Analytics"},
                new Skill { Name = "Data Architecture"},
                new Skill { Name = "Data Center"},
                new Skill { Name = "Data Engineering"},
                new Skill { Name = "Data Management"},
                new Skill { Name = "Data Mining"},
                new Skill { Name = "Data Science"},
                new Skill { Name = "Django"},
                new Skill { Name = "Drupal"},
                new Skill { Name = "Dynamics"},
                new Skill { Name = "Dynamics 365"},
                new Skill { Name = "Dynamics AX"},
                new Skill { Name = "Dynamics CRM"},
                new Skill { Name = "Dynamics GP"},
                new Skill { Name = "Dynamics NAV"},
                new Skill { Name = "Dynamics SL"},
                new Skill { Name = "Eclipse"},
                new Skill { Name = "Elasticsearch"},
                new Skill { Name = "Electron"},
                new Skill { Name = "Ember.js"},
                new Skill { Name = "EmberJS"},
                new Skill { Name = "Entity Framework"},
                new Skill { Name = "Erlang"},
                new Skill { Name = "ERP"},
                new Skill { Name = "ES6"},
                new Skill { Name = "Ethereum"},
                new Skill { Name = "Excel"},
                new Skill { Name = "Express.js"},
                new Skill { Name = "F#"},
                new Skill { Name = "Facebook"},
                new Skill { Name = "Facebook API"},
                new Skill { Name = "Facebook Marketing"},
                new Skill { Name = "Facebook Pixel"},
                new Skill { Name = "Facebook SDK"},
                new Skill { Name = "Facebook Share"},
                new Skill { Name = "Facebook Shops"},
                new Skill { Name = "Facebook Store"},
                new Skill { Name = "Facebook Technologies"},
                new Skill { Name = "Facebook Video"},
                new Skill { Name = "Facebook Watch"},
                new Skill { Name = "Firebase"},
                new Skill { Name = "Firebird"},
                new Skill { Name = "Firebug"},
                new Skill { Name = "Firefox"},
                new Skill { Name = "Firewall"},
                new Skill { Name = "Flash"},
                new Skill { Name = "Flask"},
                new Skill { Name = "Flex"},
                new Skill { Name = "Flink"},
                new Skill { Name = "Flutter"},
                new Skill { Name = "Fortran"},
                new Skill { Name = "Foundation"},
                new Skill { Name = "FreeBSD"},
                new Skill { Name = "Front-End Development"},
                new Skill { Name = "Full Stack Development"},
                new Skill { Name = "Game Development"},
                new Skill { Name = "Game Programming"},
                new Skill { Name = "Game Testing"},
                new Skill { Name = "Gatsby"},
                new Skill { Name = "GCP"},
                new Skill { Name = "GCP Cloud Functions"},
                new Skill { Name = "GCP Cloud Storage"},
                new Skill { Name = "GCP Compute Engine"},
                new Skill { Name = "GCP Datastore"},
                new Skill { Name = "GCP Functions"},
                new Skill { Name = "GCP Services"},
                new Skill { Name = "GCP Storage"},
                new Skill { Name = "GCP Technologies"},
                new Skill { Name = "GCP Virtual Machines"},
                new Skill { Name = "GCP VMs"},
                new Skill { Name = "GCP Web Services"},
                new Skill { Name = "GDB"},
                new Skill { Name = "GIMP"},
                new Skill { Name = "Git"},
                new Skill { Name = "GitHub"},
                new Skill { Name = "GitLab"},
                new Skill { Name = "Go"},
                new Skill { Name = "Google"},
                new Skill { Name = "Google AdSense"},
                new Skill { Name = "Google AdWords"},
                new Skill { Name = "Google Analytics"},
                new Skill { Name = "Google App Engine"},
                new Skill { Name = "Grails"},
                new Skill { Name = "GraphQL"},
                new Skill { Name = "Groovy"},
                new Skill { Name = "Gulp.js"},
                new Skill { Name = "Hadoop"},
                new Skill { Name = "Haskell"},
                new Skill { Name = "HBase"},
                new Skill { Name = "HDFS"},
                new Skill { Name = "Heroku"},
                new Skill { Name = "Hibernate"},
                new Skill { Name = "Highcharts"},
                new Skill { Name = "Hive"},
                new Skill { Name = "HTML"},
                new Skill { Name = "HTML5"},
                new Skill { Name = "HTTP"},
                new Skill { Name = "HTTPS"},
                new Skill { Name = "Hyper-V"},
                new Skill { Name = "IaaS"},
                new Skill { Name = "IBM"},
                new Skill { Name = "IBM AIX"},
                new Skill { Name = "IBM AS/400"},
                new Skill { Name = "IBM BPM"},
                new Skill { Name = "IBM Cognos"},
                new Skill { Name = "IBM DB2"},
                new Skill { Name = "IBM Domino"},
                new Skill { Name = "IBM iSeries"},
                new Skill { Name = "IBM Lotus Notes"},
                new Skill { Name = "IBM Mainframe"},
                new Skill { Name = "IBM MQ"},
                new Skill { Name = "IBM Rational"},
                new Skill { Name = "IBM SPSS"},
                new Skill { Name = "IBM Tivoli"},
                new Skill { Name = "IBM WebSphere"},
                new Skill { Name = "IBM Websphere MQ"},
                new Skill { Name = "IBM Websphere Portal"},
                new Skill { Name = "IBM Websphere Process Server"},
                new Skill { Name = "IBM Websphere Transformation Extender"},
                new Skill { Name = "IBM Websphere XD"},
                new Skill { Name = "Jasper"},
                new Skill { Name = "JasperReports"},
                new Skill { Name = "Java"},
                new Skill { Name = "Java 8"},
                new Skill { Name = "Java EE"},
                new Skill { Name = "Java ME"},
                new Skill { Name = "Java SE"},
                new Skill { Name = "Java Servlets"},
                new Skill { Name = "Java Spring"},
                new Skill { Name = "Java Technologies"},
                new Skill { Name = "Java Web Services"},
                new Skill { Name = "JavaScript"},
                new Skill { Name = "JavaScript Frameworks"},
                new Skill { Name = "JavaScript Libraries"},
                new Skill { Name = "Jenkins"},
                new Skill { Name = "JIRA"},
                new Skill { Name = "Joomla"},
                new Skill { Name = "jQuery"},
                new Skill { Name = "JSF"},
                new Skill { Name = "JSON"},
                new Skill { Name = "JSP"},
                new Skill { Name = "JUnit"},
                new Skill { Name = "Kafka"},
                new Skill { Name = "Kali Linux"},
                new Skill { Name = "Kanban"},
                new Skill { Name = "Kendo UI"},
                new Skill { Name = "Keras"},
                new Skill { Name = "Kibana"},
                new Skill { Name = "Kotlin"},
                new Skill { Name = "Kubernetes"},
                new Skill { Name = "LAMP"},
                new Skill { Name = "Laravel"},
                new Skill { Name = "LaTeX"},
                new Skill { Name = "LESS"},
                new Skill { Name = "Linux"},
                new Skill { Name = "Linux Administration"},
                new Skill { Name = "Linux Kernel"},
                new Skill { Name = "Linux System Administration"},
                new Skill { Name = "Linux Technologies"},
                new Skill { Name = "Linux/Unix"},
                new Skill { Name = "Load Balancing"},
                new Skill { Name = "Logstash"},
                new Skill { Name = "Lotus Domino"},
                new Skill { Name = "Lua"},
                new Skill { Name = "Lumen"},
                new Skill { Name = "Machine Learning"},
                new Skill { Name = "Magento"},
                new Skill { Name = "Mainframe"},
                new Skill { Name = "MariaDB"},
                new Skill { Name = "Matlab"},
                new Skill { Name = "Maven"},
                new Skill { Name = "MDX"},
                new Skill { Name = "Memcached"},
                new Skill { Name = "Mercurial"},
                new Skill { Name = "Meteor"},
                new Skill { Name = "Microsoft"},
                new Skill { Name = "Microsoft .NET"},
                new Skill { Name = "Microsoft Access"},
                new Skill { Name = "Microsoft Azure"},
                new Skill { Name = "Microsoft Dynamics"},
                new Skill { Name = "Microsoft Excel"},
                new Skill { Name = "Microsoft Exchange"},
                new Skill { Name = "Microsoft Office"},
                new Skill { Name = "Microsoft Outlook"},
                new Skill { Name = "Microsoft Power BI"},
                new Skill { Name = "Microsoft Project"},
                new Skill { Name = "Microsoft SQL Server"},
                new Skill { Name = "Microsoft Teams"},
                new Skill { Name = "Microsoft Technologies"},
                new Skill { Name = "Microsoft Visio"},
                new Skill { Name = "Microsoft Windows"},
                new Skill { Name = "Microsoft Word"},
                new Skill { Name = "Microsoft XNA"},
                new Skill { Name = "Microsoft.NET"},
                new Skill { Name = "MikroTik"},
                new Skill { Name = "MongoDB"},
                new Skill { Name = "Moodle"},
                new Skill { Name = "MS SQL"},
                new Skill { Name = "MS SQL Server"},
                new Skill { Name = "MS Windows"},
                new Skill { Name = "MSMQ"},
                new Skill { Name = "MSSQL"},
                new Skill { Name = "MVC"},
                new Skill { Name = "MySQL"},
                new Skill { Name = "Nagios"},
                new Skill { Name = "Nginx"},
                new Skill { Name = "Node.js"},
                new Skill { Name = "NoSQL"},
                new Skill { Name = "NPM"},
                new Skill { Name = "Numpy"},
                new Skill { Name = "Oauth"},
                new Skill { Name = "Objective-C"},
                new Skill { Name = "OCaml"},
                new Skill { Name = "ODBC"},
                new Skill { Name = "Office 365"},
                new Skill { Name = "Open Source"},
                new Skill { Name = "OpenCart"},
                new Skill { Name = "OpenGL"},
                new Skill { Name = "OpenShift"},
                new Skill { Name = "OpenStack"},
                new Skill { Name = "Oracle"},
                new Skill { Name = "Pandas"},
                new Skill { Name = "Pascal"},
                new Skill { Name = "PayPal"},
                new Skill { Name = "Pentaho"},
                new Skill { Name = "Perl"},
                new Skill { Name = "PHP"},
                new Skill { Name = "Plesk"},
                new Skill { Name = "PL/SQL"},
                new Skill { Name = "PostgreSQL"},
                new Skill { Name = "Power BI"},
                new Skill { Name = "PowerShell"},
                new Skill { Name = "Prolog"},
                new Skill { Name = "Puppet"},
                new Skill { Name = "Python"},
                new Skill { Name = "Python 2"},
                new Skill { Name = "Python 3"},
                new Skill { Name = "QlikView"},
                new Skill { Name = "Qt"},
                new Skill { Name = "R"},
                new Skill { Name = "RabbitMQ"},
                new Skill { Name = "React"},
                new Skill { Name = "React Native"},
                new Skill { Name = "Redis"},
                new Skill { Name = "Redux"},
                new Skill { Name = "REST"},
                new Skill { Name = "RESTful"},
                new Skill { Name = "RESTful Web Services"},
                new Skill { Name = "Revit"},
                new Skill { Name = "RHEL"},
                new Skill { Name = "Robot Framework"},
                new Skill { Name = "Ruby"},
                new Skill { Name = "Ruby on Rails"},
                new Skill { Name = "Rust"},
                new Skill { Name = "SaaS"},
                new Skill { Name = "SAP"},
                new Skill { Name = "Scala"},
                new Skill { Name = "Scheme"},
                new Skill { Name = "SCSS"},
                new Skill { Name = "Security"},
                new Skill { Name = "Selenium"},
                new Skill { Name = "SEO"},
                new Skill { Name = "SharePoint"},
                new Skill { Name = "Shell"},
                new Skill { Name = "Shopify"},
                new Skill { Name = "Silverlight"},
                new Skill { Name = "Sinatra"},
                new Skill { Name = "Sketch"},
                new Skill { Name = "Slack"},
                new Skill { Name = "Smalltalk"},
                new Skill { Name = "Smarty"},
                new Skill { Name = "SOAP"},
                new Skill { Name = "Software Development"},
                new Skill { Name = "Software Engineering"},
                new Skill { Name = "Software Testing"},
                new Skill { Name = "Solidity"},
                new Skill { Name = "Spring"},
                new Skill { Name = "Spring Boot"},
                new Skill { Name = "Spring Framework"},
                new Skill { Name = "Spring MVC"},
                new Skill { Name = "SQL"},
                new Skill { Name = "SQL Server"},
                new Skill { Name = "SQLite"},
                new Skill { Name = "SSIS"},
                new Skill { Name = "SSRS"},
                new Skill { Name = "TeamCity"},
                new Skill { Name = "Telematics"},
                new Skill { Name = "TestRail"},
                new Skill { Name = "Tomcat"},
                new Skill { Name = "TravisCI"},
                new Skill { Name = "TypeScript"},
                new Skill { Name = "Ubuntu"},
                new Skill { Name = "UI/UX"},
                new Skill { Name = "Unity"},
                new Skill { Name = "Unix"},
                new Skill { Name = "Unix Administration"},
                new Skill { Name = "Unix Shell Scripting"},
                new Skill { Name = "Unix System Administration"},
                new Skill { Name = "Unix Technologies"},
                new Skill { Name = "Unix/Linux"},
                new Skill { Name = "Vagrant"},
                new Skill { Name = "VB.NET"},
                new Skill { Name = "VBA"},
                new Skill { Name = "VBScript"},
                new Skill { Name = "Verilog"},
                new Skill { Name = "VHDL"},
                new Skill { Name = "VirtualBox"},
                new Skill { Name = "Virtualization"},
                new Skill { Name = "Visual Basic"},
                new Skill { Name = "Visual Basic .NET"},
                new Skill { Name = "Visual C++"},
                new Skill { Name = "Visual Studio"},
                new Skill { Name = "Visual Studio Code"},
                new Skill { Name = "VMware"},
                new Skill { Name = "Vue.js"},
                new Skill { Name = "WCF"},
                new Skill { Name = "Web Development"},
                new Skill { Name = "Web Services"},
                new Skill { Name = "Web Technologies"},
                new Skill { Name = "WebGL"},
                new Skill { Name = "WebRTC"},
                new Skill { Name = "WebSockets"},
                new Skill { Name = "WebSphere"},
                new Skill { Name = "WebStorm"},
                new Skill { Name = "Windows"},
                new Skill { Name = "Windows 10"},
                new Skill { Name = "Windows 7"},
                new Skill { Name = "Windows 8"},
                new Skill { Name = "Windows Server"},
                new Skill { Name = "Windows Server Administration"},
                new Skill { Name = "Windows Technologies"},
                new Skill { Name = "Windows Vista"},
                new Skill { Name = "Windows XP"},
                new Skill { Name = "WooCommerce"},
                new Skill { Name = "WordPress"},
                new Skill { Name = "WPF"},
                new Skill { Name = "WSO2"},
                new Skill { Name = "Xamarin"},
                new Skill { Name = "XAML"},
                new Skill { Name = "XPATH"},
                new Skill { Name = "Xen"},
                new Skill { Name = "XenServer"},
                new Skill { Name = "XML"},
                new Skill { Name = "XSLT"},
                new Skill { Name = "Yii"},
                new Skill { Name = "Zend"},
                new Skill { Name = "Zoho"},
                new Skill { Name = "ZooKeeper"},
                new Skill { Name = "Zope"},
                new Skill { Name = "SCRUM"},
                new Skill { Name = "Confluence"},
                new Skill { Name = ".NET"},
                new Skill { Name = "Cypress"},
                new Skill { Name = "Docker"},
                new Skill { Name = "Next.js"},
                new Skill { Name = "DevOps"},
                new Skill { Name = "OOP"},
                new Skill { Name = "Microservices" }
             );

            _context.SaveChanges();
         

            return StatusCode(StatusCodes.Status200OK);
        }

       
    }
}
